if: tag IS blank
language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm i -g npm@6
  - npm ci
node_js:
  - 8.10.0
script:
  - npm test
after_success:
  - git config user.email "${GIT_COMMITTER_EMAIL}"
  - git config user.name "${GIT_COMMITTER_NAME}"
  - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - |
    if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
      git checkout ${TRAVIS_BRANCH}
      printf "//registry.npmjs.org/:_authToken=$NPM_TOKEN\n" > ~/.npmrc
      npm run release
    fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
