if: tag IS blank
language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm i -g npm@6
  - npm ci
node_js:
  - lts/*
script:
  - npm run test:ci
after_success:
  - git config user.email "${GIT_COMMITTER_EMAIL}"
  - git config user.name "${GIT_COMMITTER_NAME}"
  - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - test "${TRAVIS_PULL_REQUEST}" = "false" && git checkout ${TRAVIS_BRANCH} && npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
