# Round the coverage up, up to the 2nd decimal point. E.g
# 89.0199 % => 89.02%
coverage:
  precision: 2
  round: up

  # Patch is currently disable until cypress coverage is implemented.
  status:
    patch: off

# Make the layout of the comment posted on the PR by the codecov bot a bit nicer
comment:
  layout: "files"
  behavior: once
