name: e2e tests

on: [push]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        containers: [1, 2, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run e2e tests
        uses: cypress-io/github-action@v1
        with:
          record: true
          parallel: true
          group: "GitHub Actions"
          start: npm run cy:prod
          wait-on: "http://localhost:3001"
          wait-on-timeout: 180
          env: HEADLESS=true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
