name: Eslint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      # - uses: bradennapier/eslint-plus-action@v2
      - uses: luisherranz/eslint-plus-action@npm-install-input
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          npmInstall: false
